import numpy as np

# -------------------------------------------------------
# 파일 경로 설정 (스크립트 디렉터리에서 실행한다고 가정)
# -------------------------------------------------------
WEIGHT_FILE = "../../data/_base_npy/layer2_0_weight.npy"
OUTPUT_HEX  = "../../data/weights_simd/conv2_weights_simd.hex"
OUTPUT_H    = "../../data/weights_simd/conv2_weights_simd.h"

# -------------------------------------------------------
# Packing 정책
# -------------------------------------------------------
# 페어링: W0 = W[k, ic, kh, kw], W1 = W[k+8, ic, kh, kw], k = 0..7
# 순회   : (k, ic, kh, kw) outer-to-inner — 페어별로 연속 배치
# 형식   : A_port = W1 * 2^17 + W0  (정수 등식, 25-bit 2의 보수 비트 패턴)
#          MSB 7비트는 0으로 zero-extend 하여 32-bit AXI word 생성
PAIR_STRIDE = 8     # 페어 절반 간격 (W1 채널 = W0 채널 + 8)
NUM_PAIRS   = 8     # 16 out_ch / 2

# -------------------------------------------------------
# Weight 로드
# -------------------------------------------------------
w = np.load(WEIGHT_FILE)   # (16, 8, 3, 3), int8
assert w.shape == (16, 8, 3, 3), f"unexpected weight shape: {w.shape}"
assert w.dtype == np.int8,        f"unexpected weight dtype: {w.dtype}"
print(f"[Load] weight shape={w.shape}, dtype={w.dtype}")

OUT_CH, IN_CH, KH, KW = w.shape

# -------------------------------------------------------
# Packing
# -------------------------------------------------------
MASK_25 = (1 << 25) - 1
MASK_32 = (1 << 32) - 1

packed = []     # list of 32-bit unsigned ints
ovf_count = 0   # 명세 §3.1 의 오버플로우 (W1 = -128, W0 < 0)

for k in range(NUM_PAIRS):
    for ic in range(IN_CH):
        for kh in range(KH):
            for kw in range(KW):
                w0 = int(w[k,               ic, kh, kw])
                w1 = int(w[k + PAIR_STRIDE, ic, kh, kw])

                # A_port = W1 * 2^17 + W0 (signed) → 25-bit 비트 패턴
                a_port_int = w1 * (1 << 17) + w0
                pattern_25 = a_port_int & MASK_25
                packed_32  = pattern_25 & MASK_32   # 상위 7비트 = 0

                packed.append(packed_32)

                if w1 == -128 and w0 < 0:
                    ovf_count += 1

assert len(packed) == NUM_PAIRS * IN_CH * KH * KW
print(f"[Pack] entries={len(packed)}  ovf_cases={ovf_count}/{len(packed)}")
print(f"[Pack] sample[0..3] = {[f'0x{v:08X}' for v in packed[:4]]}")

# -------------------------------------------------------
# Hex 파일 출력 (32-bit / line, 8 hex chars, uppercase)
# -------------------------------------------------------
with open(OUTPUT_HEX, "w") as f:
    for v in packed:
        f.write(f"{v:08X}\n")
print(f"[Write] {OUTPUT_HEX}  ({len(packed)} lines, {len(packed)*4} bytes)")

# -------------------------------------------------------
# C 헤더 출력
# -------------------------------------------------------
guard = "CONV2_WEIGHTS_SIMD_H"
lines = []
lines.append(f"#ifndef {guard}")
lines.append(f"#define {guard}")
lines.append("")
lines.append("#include <stdint.h>")
lines.append("")
lines.append(f"// auto-generated by scripts/header_hex_gen/conv2_simd_pack.py")
lines.append(f"// source weight : layer2_0_weight.npy  shape=(16, 8, 3, 3) int8")
lines.append(f"// pairing       : W0=W[k,ic,kh,kw], W1=W[k+8,ic,kh,kw], k=0..7")
lines.append(f"// layout        : (pair, ic, kh, kw) outer-to-inner")
lines.append(f"// element       : A_port = W1*2^17 + W0  (25-bit 2's complement)")
lines.append(f"//                 zero-extended to 32-bit (MSB 7 bits = 0)")
lines.append("")
lines.append(f"#define CONV2_SIMD_NUM_PAIRS  {NUM_PAIRS}")
lines.append(f"#define CONV2_SIMD_PAIR_STRIDE {PAIR_STRIDE}")
lines.append(f"#define CONV2_SIMD_IN_CH      {IN_CH}")
lines.append(f"#define CONV2_SIMD_KH         {KH}")
lines.append(f"#define CONV2_SIMD_KW         {KW}")
lines.append(f"#define CONV2_SIMD_LEN        {len(packed)}")
lines.append("")
lines.append(f"static const uint32_t conv2_weights_simd[CONV2_SIMD_LEN] = {{")

# 한 줄에 4개씩 (가독성)
PER_LINE = 4
for i in range(0, len(packed), PER_LINE):
    chunk = packed[i:i+PER_LINE]
    body  = ", ".join(f"0x{v:08X}u" for v in chunk)
    comma = "," if i + PER_LINE < len(packed) else ""
    lines.append(f"    {body}{comma}")

lines.append("};")
lines.append("")
lines.append(f"#endif // {guard}")
lines.append("")

with open(OUTPUT_H, "w") as f:
    f.write("\n".join(lines))
print(f"[Write] {OUTPUT_H}")

# ====================================================================================
# Verification!!
# ====================================================================================
def simd_decode(aport_25bit, x):
    """
    SIMD packing 결과를 받아 mul0, mul1 추출
    DSP의 25 × 18 signed multiplication 동작 시뮬레이션
    """
    # 25-bit signed 해석
    if aport_25bit & 0x1000000:
        aport_signed = aport_25bit - 0x2000000
    else:
        aport_signed = aport_25bit

    # x도 signed
    x_signed = x if x < 128 else x - 256  # int8

    # Multiplication
    p = aport_signed * x_signed  # signed

    # Extract mul0 (lower 17 bits as 17-bit signed)
    mul0_bits = p & 0x1FFFF
    mul0 = mul0_bits - 0x20000 if mul0_bits & 0x10000 else mul0_bits

    # Extract mul1 (bits [32:17] as 16-bit signed)
    mul1_bits = (p >> 17) & 0xFFFF
    mul1 = mul1_bits - 0x10000 if mul1_bits & 0x8000 else mul1_bits

    # Carry correction
    if mul0 < 0:
        mul1 += 1

    return mul0, mul1


# Verification
for w0 in range(-127, 128):  # -128 제외
    for w1 in range(-127, 128):
        for x in range(-128, 128):
            # Pack
            aport_int = w1 * (1 << 17) + w0
            aport_25 = aport_int & 0x01FFFFFF

            # Decode (DSP simulation)
            mul0, mul1 = simd_decode(aport_25, x & 0xFF)

            # Expected
            expected_mul0 = w0 * x
            expected_mul1 = w1 * x

            assert mul0 == expected_mul0, f"w0={w0} w1={w1} x={x}: mul0={mul0} expected={expected_mul0}"
            assert mul1 == expected_mul1, f"w0={w0} w1={w1} x={x}: mul1={mul1} expected={expected_mul1}"

print("Exhaustive verification passed: 254 × 254 × 256 cases")
