"""
weight_simd_pack.py
===================
conv1 / conv2 / fc 의 SIMD weight packing 을 한 스크립트로 통합.

공통 식 : A_port = W1 * 2^17 + W0   (25-bit 2's complement, 32-bit zero-extend)
          → DSP48E1 한 곱셈으로 (W0*X, W1*X) 동시 추출
layer 별 : OC pairing 과 순회(addr layout) 만 다름

생성 (data/weights_simd/):
  conv1_weights_simd.{hex,h}   (36   entries)
  conv2_weights_simd.{hex,h}   (576  entries)
  fc_weights_simd.{hex,h}      (11520 entries)

실행: python3 scripts/weights/weight_simd_pack.py   (어디서 실행해도 동작)
"""
import os
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
def npy(f): return os.path.join(HERE, "../../data/_base_npy", f)
def out(f): return os.path.join(HERE, "../../data/weights_simd", f)

MASK_25 = (1 << 25) - 1

# ---------------------------------------------------------------------------
# 공통 packing / decode / 출력
# ---------------------------------------------------------------------------
def pack(w0, w1):
    """A_port = W1*2^17 + W0 (25-bit 2's complement bit pattern)."""
    return (w1 * (1 << 17) + w0) & MASK_25

def simd_decode(aport_25, x_u8):
    """DSP48E1 25x18 signed mult 후 mul0=W0*X, mul1=W1*X 추출 모델."""
    a  = aport_25 - (1 << 25) if aport_25 & (1 << 24) else aport_25
    xs = x_u8 - 256 if x_u8 & 0x80 else x_u8
    p  = a * xs
    m0b = p & 0x1FFFF;        m0 = m0b - 0x20000 if m0b & 0x10000 else m0b
    m1b = (p >> 17) & 0xFFFF; m1 = m1b - 0x10000 if m1b & 0x8000 else m1b
    if m0 < 0:
        m1 += 1
    return m0, m1

def write_hex(packed, path):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        for v in packed:
            f.write(f"{v:08X}\n")
    print(f"  [hex] {os.path.basename(path):28s} {len(packed)} lines")

def write_header(packed, path, arr, guard, comment, defines):
    L = [f"#ifndef {guard}", f"#define {guard}", "", "#include <stdint.h>", ""]
    L += [f"// {c}" for c in comment] + [""]
    L += defines + [f"#define {guard[:-2]}_LEN  {len(packed)}", ""]
    L += [f"static const uint32_t {arr}[{guard[:-2]}_LEN] = {{"]
    for i in range(0, len(packed), 4):
        body = ", ".join(f"0x{v:08X}u" for v in packed[i:i + 4])
        L.append("    " + body + ("," if i + 4 < len(packed) else ""))
    L += ["};", "", f"#endif // {guard}", ""]
    with open(path, "w") as f:
        f.write("\n".join(L))
    print(f"  [h]   {os.path.basename(path)}")

# ---------------------------------------------------------------------------
# Conv1 : 18 PE = 2 group x 9 PE (3KH x 3KW), DEPTH=2 (sel=round1/2)
#   addr 0-8 g1sel0 / 9-17 g2sel0 / 18-26 g1sel1 / 27-35 g2sel1
#   (sel,group)->oc: base = sel*4 + (group-1)*2,  W0=oc(base), W1=oc(base+1)
# ---------------------------------------------------------------------------
def pack_conv1():
    w = np.load(npy("layer1_0_weight.npy"))            # (8,1,3,3) int8
    assert w.shape == (8, 1, 3, 3), f"conv1 weight shape {w.shape}"
    def decode_addr(a):
        if a < 9:  return (1, 0, a)
        if a < 18: return (2, 0, a - 9)
        if a < 27: return (1, 1, a - 18)
        return (2, 1, a - 27)
    packed = [0] * 36
    usage  = np.zeros((8, 3, 3), int)
    for a in range(36):
        g, sel, pe = decode_addr(a)
        kh, kw = pe // 3, pe % 3
        base = sel * 4 + (g - 1) * 2
        w0, w1 = int(w[base, 0, kh, kw]), int(w[base + 1, 0, kh, kw])
        packed[a] = pack(w0, w1)
        usage[base, kh, kw] += 1; usage[base + 1, kh, kw] += 1
        m0, m1 = simd_decode(packed[a], 1)             # layout self-check
        assert (m0, m1) == (w0, w1)
    assert (usage == 1).all(), "conv1 weight coverage broken"
    comment = ["auto-generated by scripts/weights/weight_simd_pack.py",
               "source : layer1_0_weight.npy (8,1,3,3) int8",
               "18 PE = 2 group x 9 PE (3KH x 3KW), DEPTH=2 (sel=round1/2)",
               "addr 0-8 g1sel0 / 9-17 g2sel0 / 18-26 g1sel1 / 27-35 g2sel1",
               "PE idx i -> (kh,kw)=(i/3,i%3); element A_port=W1*2^17+W0"]
    defines = ["#define CONV1_SIMD_NUM_PE_PER_GROUP  9",
               "#define CONV1_SIMD_NUM_GROUP         2",
               "#define CONV1_SIMD_NUM_ROUND         2", ""]
    return packed, "conv1_weights_simd", "CONV1_WEIGHTS_SIMD_H", comment, defines

# ---------------------------------------------------------------------------
# Conv2 : W0=W[k], W1=W[k+8], k=0..7 ; order (k, ic, kh, kw) -> 576
# ---------------------------------------------------------------------------
def pack_conv2():
    w = np.load(npy("layer2_0_weight.npy"))            # (16,8,3,3) int8
    assert w.shape == (16, 8, 3, 3), f"conv2 weight shape {w.shape}"
    packed = []
    for k in range(8):
        for ic in range(8):
            for kh in range(3):
                for kw in range(3):
                    w0, w1 = int(w[k, ic, kh, kw]), int(w[k + 8, ic, kh, kw])
                    p = pack(w0, w1); packed.append(p)
                    assert simd_decode(p, 1) == (w0, w1)   # layout self-check
    comment = ["auto-generated by scripts/weights/weight_simd_pack.py",
               "source : layer2_0_weight.npy (16,8,3,3) int8",
               "pairing W0=W[k], W1=W[k+8], k=0..7 ; order (k,ic,kh,kw)",
               "element A_port = W1*2^17 + W0 (25-bit, 32-bit ext)"]
    defines = ["#define CONV2_SIMD_NUM_PAIRS  8",
               "#define CONV2_SIMD_PAIR_STRIDE 8",
               "#define CONV2_SIMD_IN_CH      8",
               "#define CONV2_SIMD_KH         3",
               "#define CONV2_SIMD_KW         3", ""]
    return packed, "conv2_weights_simd", "CONV2_WEIGHTS_SIMD_H", comment, defines

# ---------------------------------------------------------------------------
# FC : W0=fc1[2*pair,j], W1=fc1[2*pair+1,j], j=c*144+s ; order (pair,s,c)
#      line_idx = pair*144*16 + s*16 + c  (RTL BRAM addr = pair*144 + s, 16ch/word)
# ---------------------------------------------------------------------------
def pack_fc():
    w = np.load(npy("fc1_weight.npy"))                 # (10,2304) int8
    assert w.shape == (10, 2304), f"fc weight shape {w.shape}"
    packed = []
    for pair in range(5):
        for s in range(144):
            for c in range(16):
                j = c * 144 + s
                w0, w1 = int(w[2 * pair, j]), int(w[2 * pair + 1, j])
                p = pack(w0, w1); packed.append(p)
                assert simd_decode(p, 1) == (w0, w1)       # layout self-check
    comment = ["auto-generated by scripts/weights/weight_simd_pack.py",
               "source : fc1_weight.npy (10,2304) int8",
               "pairing W0=fc1[2*pair,j], W1=fc1[2*pair+1,j], j=c*144+s",
               "order (pair,s,c); line = pair*144*16 + s*16 + c",
               "element A_port = W1*2^17 + W0 (25-bit, 32-bit ext)"]
    defines = ["#define FC_SIMD_NUM_PAIRS 5",
               "#define FC_SIMD_SPATIAL   144",
               "#define FC_SIMD_CHANNELS  16", ""]
    return packed, "fc_weights_simd", "FC_WEIGHTS_SIMD_H", comment, defines

# ---------------------------------------------------------------------------
def verify_packing_exhaustive():
    print("[verify] exhaustive SIMD decode (254 x 254 x 256) ...")
    for w0 in range(-127, 128):
        for w1 in range(-127, 128):
            ap = pack(w0, w1)
            for x in range(-128, 128):
                m0, m1 = simd_decode(ap, x & 0xFF)
                assert m0 == w0 * x and m1 == w1 * x
    print("[verify] PASS — packing formula holds for all W0,W1,X")

def main():
    print("=== SIMD weight packing : conv1 / conv2 / fc ===")
    for packer in (pack_conv1, pack_conv2, pack_fc):
        packed, arr, guard, comment, defines = packer()
        print(f"[{arr}]")
        write_hex(packed, out(arr + ".hex"))
        write_header(packed, out(arr + ".h"), arr, guard, comment, defines)
    verify_packing_exhaustive()
    print("[done] 3 weight hex + headers generated.")

if __name__ == "__main__":
    main()
