#ifndef CONV1_WEIGHTS_SIMD_H
#define CONV1_WEIGHTS_SIMD_H

#include <stdint.h>

// auto-generated by scripts/weights/weight_simd_pack.py
// source : layer1_0_weight.npy (8,1,3,3) int8
// 18 PE = 2 group x 9 PE (3KH x 3KW), DEPTH=2 (sel=round1/2)
// addr 0-8 g1sel0 / 9-17 g2sel0 / 18-26 g1sel1 / 27-35 g2sel1
// PE idx i -> (kh,kw)=(i/3,i%3); element A_port=W1*2^17+W0

#define CONV1_SIMD_NUM_PE_PER_GROUP  9
#define CONV1_SIMD_NUM_GROUP         2
#define CONV1_SIMD_NUM_ROUND         2

#define CONV1_WEIGHTS_SIMD_LEN  36

static const uint32_t conv1_weights_simd[CONV1_WEIGHTS_SIMD_LEN] = {
    0x01ABFFD6u, 0x0068000Du, 0x0143FFDDu, 0x0083FF96u,
    0x00760035u, 0x01D0000Du, 0x00C40042u, 0x016E0030u,
    0x01B9FFD4u, 0x01E9FFD5u, 0x017C0023u, 0x00680058u,
    0x01E9FF8Eu, 0x01640055u, 0x00D3FF8Eu, 0x008DFFDDu,
    0x012E0078u, 0x010FFF95u, 0x0025FFD1u, 0x00C9FF9Du,
    0x00AE000Cu, 0x01D7FFB3u, 0x00ABFF81u, 0x00840061u,
    0x01C00013u, 0x01F7FFBEu, 0x00F60013u, 0x01BE0026u,
    0x0153FFD2u, 0x01B5FF9Fu, 0x00320004u, 0x016DFFB5u,
    0x00180029u, 0x00E80004u, 0x0081FFE0u, 0x010DFF97u
};

#endif // CONV1_WEIGHTS_SIMD_H
