#ifndef CONV1_WEIGHTS_SIMD_H
#define CONV1_WEIGHTS_SIMD_H

#include <stdint.h>

// auto-generated by scripts/weights/conv1_simd_pack.py
// source weight : layer1_0_weight.npy  shape=(8, 1, 3, 3) int8
// architecture  : 18 PE = 2 group (g1/g2) × 9 PE (3 KH × 3 KW),
//                 each PE: DEPTH=2 weight reg (sel=0/1 = round 1/2)
// OC pairing    : (sel, group) → (oc_w0, oc_w1)
//                   (0, 1)→(0, 1)  (0, 2)→(2, 3)
//                   (1, 1)→(4, 5)  (1, 2)→(6, 7)
// addr layout   :  0.. 8 = g1 sel=0 PE[0..8]
//                  9..17 = g2 sel=0 PE[0..8]
//                 18..26 = g1 sel=1 PE[0..8]
//                 27..35 = g2 sel=1 PE[0..8]
//                 PE idx i → (kh, kw) = (i/3, i%3)
// element       : A_port = W1*2^17 + W0  (25-bit 2's complement)
//                 zero-extended to 32-bit (MSB 7 bits = 0)

#define CONV1_SIMD_NUM_PE_PER_GROUP  9
#define CONV1_SIMD_NUM_GROUP         2
#define CONV1_SIMD_NUM_ROUND         2
#define CONV1_SIMD_LEN               36

static const uint32_t conv1_weights_simd[CONV1_SIMD_LEN] = {
    0x01ABFFD6u, 0x0068000Du, 0x0143FFDDu, 0x0083FF96u,
    0x00760035u, 0x01D0000Du, 0x00C40042u, 0x016E0030u,
    0x01B9FFD4u, 0x01E9FFD5u, 0x017C0023u, 0x00680058u,
    0x01E9FF8Eu, 0x01640055u, 0x00D3FF8Eu, 0x008DFFDDu,
    0x012E0078u, 0x010FFF95u, 0x0025FFD1u, 0x00C9FF9Du,
    0x00AE000Cu, 0x01D7FFB3u, 0x00ABFF81u, 0x00840061u,
    0x01C00013u, 0x01F7FFBEu, 0x00F60013u, 0x01BE0026u,
    0x0153FFD2u, 0x01B5FF9Fu, 0x00320004u, 0x016DFFB5u,
    0x00180029u, 0x00E80004u, 0x0081FFE0u, 0x010DFF97u
};

#endif // CONV1_WEIGHTS_SIMD_H
